In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup
import re
import requests
%config InlineBackend.figure_formats = ['svg']
%matplotlib inline

sns.set(context='notebook', style='whitegrid', font_scale=1.2)

In [2]:
url = 'https://www.boxofficemojo.com/chart/ww_top_lifetime_gross/?area=XWW' 

response = requests.get(url)

In [3]:
response.status_code

200

In [4]:
page = response.text

In [5]:
soup = BeautifulSoup(page, "lxml")

## Testing

In [13]:
table = soup.find(id='table').prettify()

In [14]:
print(table)

<div class="a-section imdb-scroll-table mojo-gutter-sides" id="table">
 <div class="a-section imdb-scroll-table-inner">
  <table class="a-bordered a-horizontal-stripes a-size-base a-span12 mojo-body-table mojo-table-annotated">
   <tr>
    <th class="a-text-right mojo-field-type-rank a-nowrap">
     <span title="Rank">
      Rank
     </span>
    </th>
    <th class="a-text-left mojo-field-type-title a-nowrap">
     <span title="Title">
      Title
     </span>
    </th>
    <th class="a-text-right mojo-field-type-money a-nowrap">
     <span title="Worldwide Lifetime Gross">
      Worldwide Lifetime Gross
     </span>
    </th>
    <th class="a-text-right mojo-field-type-money a-nowrap">
     <span title="Domestic Lifetime Gross">
      Domestic Lifetime Gross
     </span>
    </th>
    <th class="a-text-right mojo-field-type-percent a-nowrap">
     <span title="Domestic %">
      Domestic %
     </span>
    </th>
    <th class="a-text-right mojo-field-type-money a-nowrap">
     <span title="Foreign Lifetime Gross">
      Foreign Lifetime Gross
     </span>
    </th>
    <th class="a-text-right mojo-field-type-percent a-nowrap">
     <span title="Foreign %">
      Foreign %
     </span>
    </th>
    <th class="a-text-left mojo-field-type-year a-nowrap">
     <span title="Year">
      Year
     </span>
    </th>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     1
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt0499549/?ref_=bo_cso_table_1">
      Avatar
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $2,847,246,203
    </td>
    <td class="a-text-right mojo-field-type-money">
     $760,507,625
    </td>
    <td class="a-text-right mojo-field-type-percent">
     26.7%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $2,086,738,578
    </td>
    <td class="a-text-right mojo-field-type-percent">
     73.3%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2009/?ref_=bo_cso_table_1">
      2009
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     2
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt4154796/?ref_=bo_cso_table_2">
      Avengers: Endgame
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $2,797,501,328
    </td>
    <td class="a-text-right mojo-field-type-money">
     $858,373,000
    </td>
    <td class="a-text-right mojo-field-type-percent">
     30.7%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,939,128,328
    </td>
    <td class="a-text-right mojo-field-type-percent">
     69.3%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_2">
      2019
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     3
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt0120338/?ref_=bo_cso_table_3">
      Titanic
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $2,201,647,264
    </td>
    <td class="a-text-right mojo-field-type-money">
     $659,363,944
    </td>
    <td class="a-text-right mojo-field-type-percent">
     30%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,542,283,320
    </td>
    <td class="a-text-right mojo-field-type-percent">
     70%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/1997/?ref_=bo_cso_table_3">
      1997
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     4
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt2488496/?ref_=bo_cso_table_4">
      Star Wars: Episode VII - The Force Awakens
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $2,069,521,700
    </td>
    <td class="a-text-right mojo-field-type-money">
     $936,662,225
    </td>
    <td class="a-text-right mojo-field-type-percent">
     45.3%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,132,859,475
    </td>
    <td class="a-text-right mojo-field-type-percent">
     54.7%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_4">
      2015
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     5
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt4154756/?ref_=bo_cso_table_5">
      Avengers: Infinity War
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $2,048,359,754
    </td>
    <td class="a-text-right mojo-field-type-money">
     $678,815,482
    </td>
    <td class="a-text-right mojo-field-type-percent">
     33.1%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,369,544,272
    </td>
    <td class="a-text-right mojo-field-type-percent">
     66.9%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_5">
      2018
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     6
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt0369610/?ref_=bo_cso_table_6">
      Jurassic World
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,670,516,444
    </td>
    <td class="a-text-right mojo-field-type-money">
     $652,385,625
    </td>
    <td class="a-text-right mojo-field-type-percent">
     39%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,018,130,819
    </td>
    <td class="a-text-right mojo-field-type-percent">
     61%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_6">
      2015
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     7
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt6105098/?ref_=bo_cso_table_7">
      The Lion King
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,667,635,327
    </td>
    <td class="a-text-right mojo-field-type-money">
     $543,638,043
    </td>
    <td class="a-text-right mojo-field-type-percent">
     32.6%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,123,997,284
    </td>
    <td class="a-text-right mojo-field-type-percent">
     67.4%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_7">
      2019
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     8
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt0848228/?ref_=bo_cso_table_8">
      The Avengers
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,518,815,515
    </td>
    <td class="a-text-right mojo-field-type-money">
     $623,357,910
    </td>
    <td class="a-text-right mojo-field-type-percent">
     41%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $895,457,605
    </td>
    <td class="a-text-right mojo-field-type-percent">
     59%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_8">
      2012
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     9
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt2820852/?ref_=bo_cso_table_9">
      Furious 7
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,515,341,399
    </td>
    <td class="a-text-right mojo-field-type-money">
     $353,007,020
    </td>
    <td class="a-text-right mojo-field-type-percent">
     23.3%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,162,334,379
    </td>
    <td class="a-text-right mojo-field-type-percent">
     76.7%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_9">
      2015
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     10
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt4520988/?ref_=bo_cso_table_10">
      Frozen II
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,450,026,933
    </td>
    <td class="a-text-right mojo-field-type-money">
     $477,373,578
    </td>
    <td class="a-text-right mojo-field-type-percent">
     32.9%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $972,653,355
    </td>
    <td class="a-text-right mojo-field-type-percent">
     67.1%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_10">
      2019
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     11
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt2395427/?ref_=bo_cso_table_11">
      Avengers: Age of Ultron
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,402,809,540
    </td>
    <td class="a-text-right mojo-field-type-money">
     $459,005,868
    </td>
    <td class="a-text-right mojo-field-type-percent">
     32.7%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $943,803,672
    </td>
    <td class="a-text-right mojo-field-type-percent">
     67.3%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_11">
      2015
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     12
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt1825683/?ref_=bo_cso_table_12">
      Black Panther
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,347,597,973
    </td>
    <td class="a-text-right mojo-field-type-money">
     $700,426,566
    </td>
    <td class="a-text-right mojo-field-type-percent">
     52%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $647,171,407
    </td>
    <td class="a-text-right mojo-field-type-percent">
     48%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_12">
      2018
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     13
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt1201607/?ref_=bo_cso_table_13">
      Harry Potter and the Deathly Hallows: Part 2
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,342,321,665
    </td>
    <td class="a-text-right mojo-field-type-money">
     $381,409,310
    </td>
    <td class="a-text-right mojo-field-type-percent">
     28.4%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $960,912,355
    </td>
    <td class="a-text-right mojo-field-type-percent">
     71.6%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2011/?ref_=bo_cso_table_13">
      2011
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     14
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt2527336/?ref_=bo_cso_table_14">
      Star Wars: Episode VIII - The Last Jedi
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,332,698,830
    </td>
    <td class="a-text-right mojo-field-type-money">
     $620,181,382
    </td>
    <td class="a-text-right mojo-field-type-percent">
     46.5%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $712,517,448
    </td>
    <td class="a-text-right mojo-field-type-percent">
     53.5%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_14">
      2017
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     15
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt4881806/?ref_=bo_cso_table_15">
      Jurassic World: Fallen Kingdom
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,310,466,296
    </td>
    <td class="a-text-right mojo-field-type-money">
     $417,719,760
    </td>
    <td class="a-text-right mojo-field-type-percent">
     31.9%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $892,746,536
    </td>
    <td class="a-text-right mojo-field-type-percent">
     68.1%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_15">
      2018
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     16
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt2294629/?ref_=bo_cso_table_16">
      Frozen
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,281,508,100
    </td>
    <td class="a-text-right mojo-field-type-money">
     $400,953,009
    </td>
    <td class="a-text-right mojo-field-type-percent">
     31.3%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $880,555,091
    </td>
    <td class="a-text-right mojo-field-type-percent">
     68.7%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_16">
      2013
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     17
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt2771200/?ref_=bo_cso_table_17">
      Beauty and the Beast
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,264,434,525
    </td>
    <td class="a-text-right mojo-field-type-money">
     $504,481,165
    </td>
    <td class="a-text-right mojo-field-type-percent">
     39.9%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $759,953,360
    </td>
    <td class="a-text-right mojo-field-type-percent">
     60.1%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_17">
      2017
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     18
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt3606756/?ref_=bo_cso_table_18">
      Incredibles 2
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,244,639,527
    </td>
    <td class="a-text-right mojo-field-type-money">
     $608,581,744
    </td>
    <td class="a-text-right mojo-field-type-percent">
     48.9%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $636,057,783
    </td>
    <td class="a-text-right mojo-field-type-percent">
     51.1%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_18">
      2018
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     19
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt4630562/?ref_=bo_cso_table_19">
      The Fate of the Furious
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,236,005,118
    </td>
    <td class="a-text-right mojo-field-type-money">
     $226,008,385
    </td>
    <td class="a-text-right mojo-field-type-percent">
     18.3%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,009,996,733
    </td>
    <td class="a-text-right mojo-field-type-percent">
     81.7%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_19">
      2017
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     20
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt1300854/?ref_=bo_cso_table_20">
      Iron Man 3
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,214,811,252
    </td>
    <td class="a-text-right mojo-field-type-money">
     $409,013,994
    </td>
    <td class="a-text-right mojo-field-type-percent">
     33.7%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $805,797,258
    </td>
    <td class="a-text-right mojo-field-type-percent">
     66.3%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_20">
      2013
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     21
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt2293640/?ref_=bo_cso_table_21">
      Minions
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,159,444,662
    </td>
    <td class="a-text-right mojo-field-type-money">
     $336,045,770
    </td>
    <td class="a-text-right mojo-field-type-percent">
     29%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $823,398,892
    </td>
    <td class="a-text-right mojo-field-type-percent">
     71%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_21">
      2015
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     22
    </td>
    <td class="a-text-left mojo-field-type-title">
     <a class="a-link-normal" href="/title/tt3498820/?ref_=bo_cso_table_22">
      Captain America: Civil War
     </a>
    </td>
    <td class="a-text-right mojo-field-type-money">
     $1,153,337,496
    </td>
    <td class="a-text-right mojo-field-type-money">
     $408,084,349
    </td>
    <td class="a-text-right mojo-field-type-percent">
     35.4%
    </td>
    <td class="a-text-right mojo-field-type-money">
     $745,253,147
    </td>
    <td class="a-text-right mojo-field-type-percent">
     64.6%
    </td>
    <td class="a-text-left mojo-field-type-year">
     <a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_22">
      2016
     </a>
    </td>
   </tr>
   <tr>
    <td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">
     23
    </td>

In [22]:
for link in soup.find(id='table').find_all('a', href=True):
    print(link)

<a class="a-link-normal" href="/title/tt0499549/?ref_=bo_cso_table_1">Avatar</a>
<a class="a-link-normal" href="/year/world/2009/?ref_=bo_cso_table_1">2009</a>
<a class="a-link-normal" href="/title/tt4154796/?ref_=bo_cso_table_2">Avengers: Endgame</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_2">2019</a>
<a class="a-link-normal" href="/title/tt0120338/?ref_=bo_cso_table_3">Titanic</a>
<a class="a-link-normal" href="/year/world/1997/?ref_=bo_cso_table_3">1997</a>
<a class="a-link-normal" href="/title/tt2488496/?ref_=bo_cso_table_4">Star Wars: Episode VII - The Force Awakens</a>
<a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_4">2015</a>
<a class="a-link-normal" href="/title/tt4154756/?ref_=bo_cso_table_5">Avengers: Infinity War</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_5">2018</a>
<a class="a-link-normal" href="/title/tt0369610/?ref_=bo_cso_table_6">Jurassic World</a>
<a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_6">2015</a>
<a class="a-link-normal" href="/title/tt6105098/?ref_=bo_cso_table_7">The Lion King</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_7">2019</a>
<a class="a-link-normal" href="/title/tt0848228/?ref_=bo_cso_table_8">The Avengers</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_8">2012</a>
<a class="a-link-normal" href="/title/tt2820852/?ref_=bo_cso_table_9">Furious 7</a>
<a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_9">2015</a>
<a class="a-link-normal" href="/title/tt4520988/?ref_=bo_cso_table_10">Frozen II</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_10">2019</a>
<a class="a-link-normal" href="/title/tt2395427/?ref_=bo_cso_table_11">Avengers: Age of Ultron</a>
<a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_11">2015</a>
<a class="a-link-normal" href="/title/tt1825683/?ref_=bo_cso_table_12">Black Panther</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_12">2018</a>
<a class="a-link-normal" href="/title/tt1201607/?ref_=bo_cso_table_13">Harry Potter and the Deathly Hallows: Part 2</a>
<a class="a-link-normal" href="/year/world/2011/?ref_=bo_cso_table_13">2011</a>
<a class="a-link-normal" href="/title/tt2527336/?ref_=bo_cso_table_14">Star Wars: Episode VIII - The Last Jedi</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_14">2017</a>
<a class="a-link-normal" href="/title/tt4881806/?ref_=bo_cso_table_15">Jurassic World: Fallen Kingdom</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_15">2018</a>
<a class="a-link-normal" href="/title/tt2294629/?ref_=bo_cso_table_16">Frozen</a>
<a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_16">2013</a>
<a class="a-link-normal" href="/title/tt2771200/?ref_=bo_cso_table_17">Beauty and the Beast</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_17">2017</a>
<a class="a-link-normal" href="/title/tt3606756/?ref_=bo_cso_table_18">Incredibles 2</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_18">2018</a>
<a class="a-link-normal" href="/title/tt4630562/?ref_=bo_cso_table_19">The Fate of the Furious</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_19">2017</a>
<a class="a-link-normal" href="/title/tt1300854/?ref_=bo_cso_table_20">Iron Man 3</a>
<a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_20">2013</a>
<a class="a-link-normal" href="/title/tt2293640/?ref_=bo_cso_table_21">Minions</a>
<a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_21">2015</a>
<a class="a-link-normal" href="/title/tt3498820/?ref_=bo_cso_table_22">Captain America: Civil War</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_22">2016</a>
<a class="a-link-normal" href="/title/tt1477834/?ref_=bo_cso_table_23">Aquaman</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_23">2018</a>
<a class="a-link-normal" href="/title/tt0167260/?ref_=bo_cso_table_24">The Lord of the Rings: The Return of the King</a>
<a class="a-link-normal" href="/year/world/2003/?ref_=bo_cso_table_24">2003</a>
<a class="a-link-normal" href="/title/tt6320628/?ref_=bo_cso_table_25">Spider-Man: Far from Home</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_25">2019</a>
<a class="a-link-normal" href="/title/tt4154664/?ref_=bo_cso_table_26">Captain Marvel</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_26">2019</a>
<a class="a-link-normal" href="/title/tt1399103/?ref_=bo_cso_table_27">Transformers: Dark of the Moon</a>
<a class="a-link-normal" href="/year/world/2011/?ref_=bo_cso_table_27">2011</a>
<a class="a-link-normal" href="/title/tt1074638/?ref_=bo_cso_table_28">Skyfall</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_28">2012</a>
<a class="a-link-normal" href="/title/tt2109248/?ref_=bo_cso_table_29">Transformers: Age of Extinction</a>
<a class="a-link-normal" href="/year/world/2014/?ref_=bo_cso_table_29">2014</a>
<a class="a-link-normal" href="/title/tt1345836/?ref_=bo_cso_table_30">The Dark Knight Rises</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_30">2012</a>
<a class="a-link-normal" href="/title/tt2527338/?ref_=bo_cso_table_31">Star Wars: Episode IX - The Rise of Skywalker</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_31">2019</a>
<a class="a-link-normal" href="/title/tt7286456/?ref_=bo_cso_table_32">Joker</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_32">2019</a>
<a class="a-link-normal" href="/title/tt1979376/?ref_=bo_cso_table_33">Toy Story 4</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_33">2019</a>
<a class="a-link-normal" href="/title/tt0435761/?ref_=bo_cso_table_34">Toy Story 3</a>
<a class="a-link-normal" href="/year/world/2010/?ref_=bo_cso_table_34">2010</a>
<a class="a-link-normal" href="/title/tt0383574/?ref_=bo_cso_table_35">Pirates of the Caribbean: Dead Man's Chest</a>
<a class="a-link-normal" href="/year/world/2006/?ref_=bo_cso_table_35">2006</a>
<a class="a-link-normal" href="/title/tt0110357/?ref_=bo_cso_table_36">The Lion King</a>
<a class="a-link-normal" href="/year/world/1994/?ref_=bo_cso_table_36">1994</a>
<a class="a-link-normal" href="/title/tt3748528/?ref_=bo_cso_table_37">Rogue One: A Star Wars Story</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_37">2016</a>
<a class="a-link-normal" href="/title/tt6139732/?ref_=bo_cso_table_38">Aladdin</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_38">2019</a>
<a class="a-link-normal" href="/title/tt1298650/?ref_=bo_cso_table_39">Pirates of the Caribbean: On Stranger Tides</a>
<a class="a-link-normal" href="/year/world/2011/?ref_=bo_cso_table_39">2011</a>
<a class="a-link-normal" href="/title/tt3469046/?ref_=bo_cso_table_40">Despicable Me 3</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_40">2017</a>
<a class="a-link-normal" href="/title/tt0107290/?ref_=bo_cso_table_41">Jurassic Park</a>
<a class="a-link-normal" href="/year/world/1993/?ref_=bo_cso_table_41">1993</a>
<a class="a-link-normal" href="/title/tt2277860/?ref_=bo_cso_table_42">Finding Dory</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_42">2016</a>
<a class="a-link-normal" href="/title/tt0120915/?ref_=bo_cso_table_43">Star Wars: Episode I - The Phantom Menace</a>
<a class="a-link-normal" href="/year/world/1999/?ref_=bo_cso_table_43">1999</a>
<a class="a-link-normal" href="/title/tt1014759/?ref_=bo_cso_table_44">Alice in Wonderland</a>
<a class="a-link-normal" href="/year/world/2010/?ref_=bo_cso_table_44">2010</a>
<a class="a-link-normal" href="/title/tt2948356/?ref_=bo_cso_table_45">Zootopia</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_45">2016</a>
<a class="a-link-normal" href="/title/tt0903624/?ref_=bo_cso_table_46">The Hobbit: An Unexpected Journey</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_46">2012</a>
<a class="a-link-normal" href="/title/tt0241527/?ref_=bo_cso_table_47">Harry Potter and the Sorcerer's Stone</a>
<a class="a-link-normal" href="/year/world/2001/?ref_=bo_cso_table_47">2001</a>
<a class="a-link-normal" href="/title/tt0468569/?ref_=bo_cso_table_48">The Dark Knight</a>
<a class="a-link-normal" href="/year/world/2008/?ref_=bo_cso_table_48">2008</a>
<a class="a-link-normal" href="/title/tt0926084/?ref_=bo_cso_table_49">Harry Potter and the Deathly Hallows: Part 1</a>
<a class="a-link-normal" href="/year/world/2010/?ref_=bo_cso_table_49">2010</a>
<a class="a-link-normal" href="/title/tt1690953/?ref_=bo_cso_table_50">Despicable Me 2</a>
<a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_50">2013</a>
<a class="a-link-normal" href="/title/tt3040964/?ref_=bo_cso_table_51">The Jungle Book</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_51">2016</a>
<a class="a-link-normal" href="/title/tt2283362/?ref_=bo_cso_table_52">Jumanji: Welcome to the Jungle</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_52">2017</a>
<a class="a-link-normal" href="/title/tt2310332/?ref_=bo_cso_table_53">The Hobbit: The Battle of the Five Armies</a>
<a class="a-link-normal" href="/year/world/2014/?ref_=bo_cso_table_53">2014</a>
<a class="a-link-normal" href="/title/tt0449088/?ref_=bo_cso_table_54">Pirates of the Caribbean: At World's End</a>
<a class="a-link-normal" href="/year/world/2007/?ref_=bo_cso_table_54">2007</a>
<a class="a-link-normal" href="/title/tt1170358/?ref_=bo_cso_table_55">The Hobbit: The Desolation of Smaug</a>
<a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_55">2013</a>
<a class="a-link-normal" href="/title/tt0167261/?ref_=bo_cso_table_56">The Lord of the Rings: The Two Towers</a>
<a class="a-link-normal" href="/year/world/2002/?ref_=bo_cso_table_56">2002</a>
<a class="a-link-normal" href="/title/tt0373889/?ref_=bo_cso_table_57">Harry Potter and the Order of the Phoenix</a>
<a class="a-link-normal" href="/year/world/2007/?ref_=bo_cso_table_57">2007</a>
<a class="a-link-normal" href="/title/tt0266543/?ref_=bo_cso_table_58">Finding Nemo</a>
<a class="a-link-normal" href="/year/world/2003/?ref_=bo_cso_table_58">2003</a>
<a class="a-link-normal" href="/title/tt0417741/?ref_=bo_cso_table_59">Harry Potter and the Half-Blood Prince</a>
<a class="a-link-normal" href="/year/world/2009/?ref_=bo_cso_table_59">2009</a>
<a class="a-link-normal" href="/title/tt0298148/?ref_=bo_cso_table_60">Shrek 2</a>
<a class="a-link-normal" href="/year/world/2004/?ref_=bo_cso_table_60">2004</a>
<a class="a-link-normal" href="/title/tt1727824/?ref_=bo_cso_table_61">Bohemian Rhapsody</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_61">2018</a>
<a class="a-link-normal" href="/title/tt0120737/?ref_=bo_cso_table_62">The Lord of the Rings: The Fellowship of the Ring</a>
<a class="a-link-normal" href="/year/world/2001/?ref_=bo_cso_table_62">2001</a>
<a class="a-link-normal" href="/title/tt0330373/?ref_=bo_cso_table_63">Harry Potter and the Goblet of Fire</a>
<a class="a-link-normal" href="/year/world/2005/?ref_=bo_cso_table_63">2005</a>
<a class="a-link-normal" href="/title/tt0413300/?ref_=bo_cso_table_64">Spider-Man 3</a>
<a class="a-link-normal" href="/year/world/2007/?ref_=bo_cso_table_64">2007</a>
<a class="a-link-normal" href="/title/tt1080016/?ref_=bo_cso_table_65">Ice Age: Dawn of the Dinosaurs</a>
<a class="a-link-normal" href="/year/world/2009/?ref_=bo_cso_table_65">2009</a>
<a class="a-link-normal" href="/title/tt2379713/?ref_=bo_cso_table_66">Spectre</a>
<a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_66">2015</a>
<a class="a-link-normal" href="/title/tt2250912/?ref_=bo_cso_table_67">Spider-Man: Homecoming</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_67">2017</a>
<a class="a-link-normal" href="/title/tt0295297/?ref_=bo_cso_table_68">Harry Potter and the Chamber of Secrets</a>
<a class="a-link-normal" href="/year/world/2002/?ref_=bo_cso_table_68">2002</a>
<a class="a-link-normal" href="/title/tt1667889/?ref_=bo_cso_table_69">Ice Age: Continental Drift</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_69">2012</a>
<a class="a-link-normal" href="/title/tt2709768/?ref_=bo_cso_table_70">The Secret Life of Pets</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_70">2016</a>
<a class="a-link-normal" href="/title/tt2975590/?ref_=bo_cso_table_71">Batman v Superman: Dawn of Justice</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_71">2016</a>
<a class="a-link-normal" href="/title/tt7131870/?ref_=bo_cso_table_72">Wolf Warrior 2</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_72">2017</a>
<a class="a-link-normal" href="/title/tt0121766/?ref_=bo_cso_table_73">Star Wars: Episode III - Revenge of the Sith</a>
<a class="a-link-normal" href="/year/world/2005/?ref_=bo_cso_table_73">2005</a>
<a class="a-link-normal" href="/title/tt1951264/?ref_=bo_cso_table_74">The Hunger Games: Catching Fire</a>
<a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_74">2013</a>
<a class="a-link-normal" href="/title/tt3896198/?ref_=bo_cso_table_75">Guardians of the Galaxy Vol. 2</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_75">2017</a>
<a class="a-link-normal" href="/title/tt2096673/?ref_=bo_cso_table_76">Inside Out</a>
<a class="a-link-normal" href="/year/world/2015/?ref_=bo_cso_table_76">2015</a>
<a class="a-link-normal" href="/title/tt1270797/?ref_=bo_cso_table_77">Venom</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_77">2018</a>
<a class="a-link-normal" href="/title/tt3501632/?ref_=bo_cso_table_78">Thor: Ragnarok</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_78">2017</a>
<a class="a-link-normal" href="/title/tt1375666/?ref_=bo_cso_table_79">Inception</a>
<a class="a-link-normal" href="/year/world/2010/?ref_=bo_cso_table_79">2010</a>
<a class="a-link-normal" href="/title/tt1055369/?ref_=bo_cso_table_80">Transformers: Revenge of the Fallen</a>
<a class="a-link-normal" href="/year/world/2009/?ref_=bo_cso_table_80">2009</a>
<a class="a-link-normal" href="/title/tt1673434/?ref_=bo_cso_table_81">The Twilight Saga: Breaking Dawn - Part 2</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_81">2012</a>
<a class="a-link-normal" href="/title/tt0145487/?ref_=bo_cso_table_82">Spider-Man</a>
<a class="a-link-normal" href="/year/world/2002/?ref_=bo_cso_table_82">2002</a>
<a class="a-link-normal" href="/title/tt0451279/?ref_=bo_cso_table_83">Wonder Woman</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_83">2017</a>
<a class="a-link-normal" href="/title/tt13364790/?ref_=bo_cso_table_84">Hi, Mom</a>
<a class="a-link-normal" href="/year/world/2021/?ref_=bo_cso_table_84">2021</a>
<a class="a-link-normal" href="/title/tt0116629/?ref_=bo_cso_table_85">Independence Day</a>
<a class="a-link-normal" href="/year/world/1996/?ref_=bo_cso_table_85">1996</a>
<a class="a-link-normal" href="/title/tt3183660/?ref_=bo_cso_table_86">Fantastic Beasts and Where to Find Them</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_86">2016</a>
<a class="a-link-normal" href="/title/tt0413267/?ref_=bo_cso_table_87">Shrek the Third</a>
<a class="a-link-normal" href="/year/world/2007/?ref_=bo_cso_table_87">2007</a>
<a class="a-link-normal" href="/title/tt2380307/?ref_=bo_cso_table_88">Coco</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_88">2017</a>
<a class="a-link-normal" href="/title/tt7975244/?ref_=bo_cso_table_89">Jumanji: The Next Level</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_89">2019</a>
<a class="a-link-normal" href="/title/tt0304141/?ref_=bo_cso_table_90">Harry Potter and the Prisoner of Azkaban</a>
<a class="a-link-normal" href="/year/world/2004/?ref_=bo_cso_table_90">2004</a>
<a class="a-link-normal" href="/title/tt1790809/?ref_=bo_cso_table_91">Pirates of the Caribbean: Dead Men Tell No Tales</a>
<a class="a-link-normal" href="/year/world/2017/?ref_=bo_cso_table_91">2017</a>
<a class="a-link-normal" href="/title/tt0083866/?ref_=bo_cso_table_92">E.T. the Extra-Terrestrial</a>
<a class="a-link-normal" href="/year/world/1982/?ref_=bo_cso_table_92">1982</a>
<a class="a-link-normal" href="/title/tt4912910/?ref_=bo_cso_table_93">Mission: Impossible - Fallout</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_93">2018</a>
<a class="a-link-normal" href="/title/tt1190080/?ref_=bo_cso_table_94">2012</a>
<a class="a-link-normal" href="/year/world/2009/?ref_=bo_cso_table_94">2009</a>
<a class="a-link-normal" href="/title/tt0367882/?ref_=bo_cso_table_95">Indiana Jones and the Kingdom of the Crystal Skull</a>
<a class="a-link-normal" href="/year/world/2008/?ref_=bo_cso_table_95">2008</a>
<a class="a-link-normal" href="/title/tt0316654/?ref_=bo_cso_table_96">Spider-Man 2</a>
<a class="a-link-normal" href="/year/world/2004/?ref_=bo_cso_table_96">2004</a>
<a class="a-link-normal" href="/title/tt1905041/?ref_=bo_cso_table_97">Fast &amp; Furious 6</a>
<a class="a-link-normal" href="/year/world/2013/?ref_=bo_cso_table_97">2013</a>
<a class="a-link-normal" href="/title/tt5463162/?ref_=bo_cso_table_98">Deadpool 2</a>
<a class="a-link-normal" href="/year/world/2018/?ref_=bo_cso_table_98">2018</a>
<a class="a-link-normal" href="/title/tt1431045/?ref_=bo_cso_table_99">Deadpool</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_99">2016</a>
<a class="a-link-normal" href="/title/tt0076759/?ref_=bo_cso_table_100">Star Wars: Episode IV - A New Hope</a>
<a class="a-link-normal" href="/year/world/1977/?ref_=bo_cso_table_100">1977</a>
<a class="a-link-normal" href="/title/tt2015381/?ref_=bo_cso_table_101">Guardians of the Galaxy</a>
<a class="a-link-normal" href="/year/world/2014/?ref_=bo_cso_table_101">2014</a>
<a class="a-link-normal" href="/title/tt0382625/?ref_=bo_cso_table_102">The Da Vinci Code</a>
<a class="a-link-normal" href="/year/world/2006/?ref_=bo_cso_table_102">2006</a>
<a class="a-link-normal" href="/title/tt6806448/?ref_=bo_cso_table_103">Fast &amp; Furious Presents: Hobbs &amp; Shaw</a>
<a class="a-link-normal" href="/year/world/2019/?ref_=bo_cso_table_103">2019</a>
<a class="a-link-normal" href="/title/tt1587310/?ref_=bo_cso_table_104">Maleficent</a>
<a class="a-link-normal" href="/year/world/2014/?ref_=bo_cso_table_104">2014</a>
<a class="a-link-normal" href="/title/tt0948470/?ref_=bo_cso_table_105">The Amazing Spider-Man</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_105">2012</a>
<a class="a-link-normal" href="/title/tt1951265/?ref_=bo_cso_table_106">The Hunger Games: Mockingjay - Part 1</a>
<a class="a-link-normal" href="/year/world/2014/?ref_=bo_cso_table_106">2014</a>
<a class="a-link-normal" href="/title/tt0892791/?ref_=bo_cso_table_107">Shrek Forever After</a>
<a class="a-link-normal" href="/year/world/2010/?ref_=bo_cso_table_107">2010</a>
<a class="a-link-normal" href="/title/tt1277953/?ref_=bo_cso_table_108">Madagascar 3: Europe's Most Wanted</a>
<a class="a-link-normal" href="/year/world/2012/?ref_=bo_cso_table_108">2012</a>
<a class="a-link-normal" href="/title/tt1386697/?ref_=bo_cso_table_109">Suicide Squad</a>
<a class="a-link-normal" href="/year/world/2016/?ref_=bo_cso_table_109">2016</a>
<a class="a-link-normal" href="/title/tt1877832/?ref_=bo_cso_table_110">X-Men: Days of Future Past</a>
<a class="a-link-normal" href="/year/world/2014/?ref_=bo_cso_table_110">2014</a>
<a class="a-link-normal" href="/title/tt0363771/?ref_=bo_cso_table_111">The Chronicles of Narnia: The Lion, the Witch and the Wardrobe</a>
<a class="a-link-normal" href="/year/world/2005/?ref_=bo_cso_table_111">2005</a>
<a class="a-link-normal" href="/title/tt1453405/?ref_=bo_cso_table_112">Monsters University</a>

In [28]:
elements = [element for element in soup.find(id='table').find_all('a', href=True)]

In [30]:
links = {}
for element in elements[::2]:
    title, url = element.text, element['href']
    links[title] = [url]
    
links

{'Avatar': ['/title/tt0499549/?ref_=bo_cso_table_1'],
 'Avengers: Endgame': ['/title/tt4154796/?ref_=bo_cso_table_2'],
 'Titanic': ['/title/tt0120338/?ref_=bo_cso_table_3'],
 'Star Wars: Episode VII - The Force Awakens': ['/title/tt2488496/?ref_=bo_cso_table_4'],
 'Avengers: Infinity War': ['/title/tt4154756/?ref_=bo_cso_table_5'],
 'Jurassic World': ['/title/tt0369610/?ref_=bo_cso_table_6'],
 'The Lion King': ['/title/tt0110357/?ref_=bo_cso_table_36'],
 'The Avengers': ['/title/tt0848228/?ref_=bo_cso_table_8'],
 'Furious 7': ['/title/tt2820852/?ref_=bo_cso_table_9'],
 'Frozen II': ['/title/tt4520988/?ref_=bo_cso_table_10'],
 'Avengers: Age of Ultron': ['/title/tt2395427/?ref_=bo_cso_table_11'],
 'Black Panther': ['/title/tt1825683/?ref_=bo_cso_table_12'],
 'Harry Potter and the Deathly Hallows: Part 2': ['/title/tt1201607/?ref_=bo_cso_table_13'],
 'Star Wars: Episode VIII - The Last Jedi': ['/title/tt2527336/?ref_=bo_cso_table_14'],
 'Jurassic World: Fallen Kingdom': ['/title/tt4881806/?ref_=bo_cso_table_15'],
 'Frozen': ['/title/tt2294629/?ref_=bo_cso_table_16'],
 'Beauty and the Beast': ['/title/tt2771200/?ref_=bo_cso_table_17'],
 'Incredibles 2': ['/title/tt3606756/?ref_=bo_cso_table_18'],
 'The Fate of the Furious': ['/title/tt4630562/?ref_=bo_cso_table_19'],
 'Iron Man 3': ['/title/tt1300854/?ref_=bo_cso_table_20'],
 'Minions': ['/title/tt2293640/?ref_=bo_cso_table_21'],
 'Captain America: Civil War': ['/title/tt3498820/?ref_=bo_cso_table_22'],
 'Aquaman': ['/title/tt1477834/?ref_=bo_cso_table_23'],
 'The Lord of the Rings: The Return of the King': ['/title/tt0167260/?ref_=bo_cso_table_24'],
 'Spider-Man: Far from Home': ['/title/tt6320628/?ref_=bo_cso_table_25'],
 'Captain Marvel': ['/title/tt4154664/?ref_=bo_cso_table_26'],
 'Transformers: Dark of the Moon': ['/title/tt1399103/?ref_=bo_cso_table_27'],
 'Skyfall': ['/title/tt1074638/?ref_=bo_cso_table_28'],
 'Transformers: Age of Extinction': ['/title/tt2109248/?ref_=bo_cso_table_29'],
 'The Dark Knight Rises': ['/title/tt1345836/?ref_=bo_cso_table_30'],
 'Star Wars: Episode IX - The Rise of Skywalker': ['/title/tt2527338/?ref_=bo_cso_table_31'],
 'Joker': ['/title/tt7286456/?ref_=bo_cso_table_32'],
 'Toy Story 4': ['/title/tt1979376/?ref_=bo_cso_table_33'],
 'Toy Story 3': ['/title/tt0435761/?ref_=bo_cso_table_34'],
 "Pirates of the Caribbean: Dead Man's Chest": ['/title/tt0383574/?ref_=bo_cso_table_35'],
 'Rogue One: A Star Wars Story': ['/title/tt3748528/?ref_=bo_cso_table_37'],
 'Aladdin': ['/title/tt6139732/?ref_=bo_cso_table_38'],
 'Pirates of the Caribbean: On Stranger Tides': ['/title/tt1298650/?ref_=bo_cso_table_39'],
 'Despicable Me 3': ['/title/tt3469046/?ref_=bo_cso_table_40'],
 'Jurassic Park': ['/title/tt0107290/?ref_=bo_cso_table_41'],
 'Finding Dory': ['/title/tt2277860/?ref_=bo_cso_table_42'],
 'Star Wars: Episode I - The Phantom Menace': ['/title/tt0120915/?ref_=bo_cso_table_43'],
 'Alice in Wonderland': ['/title/tt1014759/?ref_=bo_cso_table_44'],
 'Zootopia': ['/title/tt2948356/?ref_=bo_cso_table_45'],
 'The Hobbit: An Unexpected Journey': ['/title/tt0903624/?ref_=bo_cso_table_46'],
 "Harry Potter and the Sorcerer's Stone": ['/title/tt0241527/?ref_=bo_cso_table_47'],
 'The Dark Knight': ['/title/tt0468569/?ref_=bo_cso_table_48'],
 'Harry Potter and the Deathly Hallows: Part 1': ['/title/tt0926084/?ref_=bo_cso_table_49'],
 'Despicable Me 2': ['/title/tt1690953/?ref_=bo_cso_table_50'],
 'The Jungle Book': ['/title/tt3040964/?ref_=bo_cso_table_51'],
 'Jumanji: Welcome to the Jungle': ['/title/tt2283362/?ref_=bo_cso_table_52'],
 'The Hobbit: The Battle of the Five Armies': ['/title/tt2310332/?ref_=bo_cso_table_53'],
 "Pirates of the Caribbean: At World's End": ['/title/tt0449088/?ref_=bo_cso_table_54'],
 'The Hobbit: The Desolation of Smaug': ['/title/tt1170358/?ref_=bo_cso_table_55'],
 'The Lord of the Rings: The Two Towers': ['/title/tt0167261/?ref_=bo_cso_table_56'],
 'Harry Potter and the Order of the Phoenix': ['/title/tt0373889/?ref_=bo_cso_table_57'],
 'Finding Nemo': ['/title/tt0266543/?ref_=bo_cso_table_58'],
 'Harry Potter and the Half-Blood Prince': ['/title/tt0417741/?ref_=bo_cso_table_59'],
 'Shrek 2': ['/title/tt0298148/?ref_=bo_cso_table_60'],
 'Bohemian Rhapsody': ['/title/tt1727824/?ref_=bo_cso_table_61'],
 'The Lord of the Rings: The Fellowship of the Ring': ['/title/tt0120737/?ref_=bo_cso_table_62'],
 'Harry Potter and the Goblet of Fire': ['/title/tt0330373/?ref_=bo_cso_table_63'],
 'Spider-Man 3': ['/title/tt0413300/?ref_=bo_cso_table_64'],
 'Ice Age: Dawn of the Dinosaurs': ['/title/tt1080016/?ref_=bo_cso_table_65'],
 'Spectre': ['/title/tt2379713/?ref_=bo_cso_table_66'],
 'Spider-Man: Homecoming': ['/title/tt2250912/?ref_=bo_cso_table_67'],
 'Harry Potter and the Chamber of Secrets': ['/title/tt0295297/?ref_=bo_cso_table_68'],
 'Ice Age: Continental Drift': ['/title/tt1667889/?ref_=bo_cso_table_69'],
 'The Secret Life of Pets': ['/title/tt2709768/?ref_=bo_cso_table_70'],
 'Batman v Superman: Dawn of Justice': ['/title/tt2975590/?ref_=bo_cso_table_71'],
 'Wolf Warrior 2': ['/title/tt7131870/?ref_=bo_cso_table_72'],
 'Star Wars: Episode III - Revenge of the Sith': ['/title/tt0121766/?ref_=bo_cso_table_73'],
 'The Hunger Games: Catching Fire': ['/title/tt1951264/?ref_=bo_cso_table_74'],
 'Guardians of the Galaxy Vol. 2': ['/title/tt3896198/?ref_=bo_cso_table_75'],
 'Inside Out': ['/title/tt2096673/?ref_=bo_cso_table_76'],
 'Venom': ['/title/tt1270797/?ref_=bo_cso_table_77'],
 'Thor: Ragnarok': ['/title/tt3501632/?ref_=bo_cso_table_78'],
 'Inception': ['/title/tt1375666/?ref_=bo_cso_table_79'],
 'Transformers: Revenge of the Fallen': ['/title/tt1055369/?ref_=bo_cso_table_80'],
 'The Twilight Saga: Breaking Dawn - Part 2': ['/title/tt1673434/?ref_=bo_cso_table_81'],
 'Spider-Man': ['/title/tt0145487/?ref_=bo_cso_table_82'],
 'Wonder Woman': ['/title/tt0451279/?ref_=bo_cso_table_83'],
 'Hi, Mom': ['/title/tt13364790/?ref_=bo_cso_table_84'],
 'Independence Day': ['/title/tt0116629/?ref_=bo_cso_table_85'],
 'Fantastic Beasts and Where to Find Them': ['/title/tt3183660/?ref_=bo_cso_table_86'],
 'Shrek the Third': ['/title/tt0413267/?ref_=bo_cso_table_87'],
 'Coco': ['/title/tt2380307/?ref_=bo_cso_table_88'],
 'Jumanji: The Next Level': ['/title/tt7975244/?ref_=bo_cso_table_89'],
 'Harry Potter and the Prisoner of Azkaban': ['/title/tt0304141/?ref_=bo_cso_table_90'],
 'Pirates of the Caribbean: Dead Men Tell No Tales': ['/title/tt1790809/?ref_=bo_cso_table_91'],
 'E.T. the Extra-Terrestrial': ['/title/tt0083866/?ref_=bo_cso_table_92'],
 'Mission: Impossible - Fallout': ['/title/tt4912910/?ref_=bo_cso_table_93'],
 '2012': ['/title/tt1190080/?ref_=bo_cso_table_94'],
 'Indiana Jones and the Kingdom of the Crystal Skull': ['/title/tt0367882/?ref_=bo_cso_table_95'],
 'Spider-Man 2': ['/title/tt0316654/?ref_=bo_cso_table_96'],
 'Fast & Furious 6': ['/title/tt1905041/?ref_=bo_cso_table_97'],
 'Deadpool 2': ['/title/tt5463162/?ref_=bo_cso_table_98'],
 'Deadpool': ['/title/tt1431045/?ref_=bo_cso_table_99'],
 'Star Wars: Episode IV - A New Hope': ['/title/tt0076759/?ref_=bo_cso_table_100'],
 'Guardians of the Galaxy': ['/title/tt2015381/?ref_=bo_cso_table_101'],
 'The Da Vinci Code': ['/title/tt0382625/?ref_=bo_cso_table_102'],
 'Fast & Furious Presents: Hobbs & Shaw': ['/title/tt6806448/?ref_=bo_cso_table_103'],
 'Maleficent': ['/title/tt1587310/?ref_=bo_cso_table_104'],
 'The Amazing Spider-Man': ['/title/tt0948470/?ref_=bo_cso_table_105'],
 'The Hunger Games: Mockingjay - Part 1': ['/title/tt1951265/?ref_=bo_cso_table_106'],
 'Shrek Forever After': ['/title/tt0892791/?ref_=bo_cso_table_107'],
 "Madagascar 3: Europe's Most Wanted": ['/title/tt1277953/?ref_=bo_cso_table_108'],
 'Suicide Squad': ['/title/tt1386697/?ref_=bo_cso_table_109'],
 'X-Men: Days of Future Past': ['/title/tt1877832/?ref_=bo_cso_table_110'],
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe': ['/title/tt0363771/?ref_=bo_cso_table_111'],
 'Monsters University': ['/title/tt1453405/?ref_=bo_cso_table_112'],
 'The Matrix Reloaded': ['/title/tt0234215/?ref_=bo_cso_table_113'],
 'Up': ['/title/tt1049413/?ref_=bo_cso_table_114'],
 'Ne Zha': ['/title/tt10627720/?ref_=bo_cso_table_115'],
 'Gravity': ['/title/tt1454468/?ref_=bo_cso_table_116'],
 'F9: The Fast Saga': ['/title/tt5433138/?ref_=bo_cso_table_117'],
 'Captain America: The Winter Soldier': ['/title/tt1843866/?ref_=bo_cso_table_118'],
 'The Twilight Saga: Breaking Dawn - Part 1': ['/title/tt1324999/?ref_=bo_cso_table_119'],
 'The Twilight Saga: New Moon': ['/title/tt1259571/?ref_=bo_cso_table_120'],
 'Dawn of the Planet of the Apes': ['/title/tt2103281/?ref_=bo_cso_table_121'],
 'Transformers': ['/title/tt0418279/?ref_=bo_cso_table_122'],
 'The Amazing Spider-Man 2': ['/title/tt1872181/?ref_=bo_cso_table_123'],
 'It': ['/title/tt1396484/?ref_=bo_cso_table_124'],
 'Interstellar': ['/title/tt0816692/?ref_=bo_cso_table_125'],
 'The Wandering Earth': ['/title/tt7605074/?ref_=bo_cso_table_126'],
 'The Twilight Saga: Eclipse': ['/title/tt1325004/?ref_=bo_cso_table_127'],
 'Mission: Impossible - Ghost Protocol': ['/title/tt1229238/?ref_=bo_cso_table_128'],
 'The Hunger Games': ['/title/tt1392170/?ref_=bo_cso_table_129'],
 'Detective Chinatown 3': ['/title/tt10370822/?ref_=bo_cso_table_130'],
 'Mission: Impossible - Rogue Nation': ['/title/tt2381249/?ref_=bo_cso_table_131'],
 'Forrest Gump': ['/title/tt0109830/?ref_=bo_cso_table_132'],
 'Doctor Strange': ['/title/tt1211837/?ref_=bo_cso_table_133'],
 'The Sixth Sense': ['/title/tt0167404/?ref_=bo_cso_table_134'],
 'Man of Steel': ['/title/tt0770828/?ref_=bo_cso_table_135'],
 'Ice Age: The Meltdown': ['/title/tt0438097/?ref_=bo_cso_table_136'],
 'Kung Fu Panda 2': ['/title/tt1302011/?ref_=bo_cso_table_137'],
 'The Hunger Games: Mockingjay - Part 2': ['/title/tt1951266/?ref_=bo_cso_table_138'],
 'Justice League': ['/title/tt0974015/?ref_=bo_cso_table_139'],
 'Big Hero 6': ['/title/tt2245084/?ref_=bo_cso_table_140'],
 'Fantastic Beasts: The Crimes of Grindelwald': ['/title/tt4123430/?ref_=bo_cso_table_141'],
 'Pirates of the Caribbean: The Curse of the Black Pearl': ['/title/tt0325980/?ref_=bo_cso_table_142'],
 'Star Wars: Episode II - Attack of the Clones': ['/title/tt0121765/?ref_=bo_cso_table_143'],
 'Thor: The Dark World': ['/title/tt1981115/?ref_=bo_cso_table_144'],
 'Moana': ['/title/tt3521164/?ref_=bo_cso_table_145'],
 'Sing': ['/title/tt3470600/?ref_=bo_cso_table_146'],
 'Kung Fu Panda': ['/title/tt0441773/?ref_=bo_cso_table_147'],
 'The Incredibles': ['/title/tt0317705/?ref_=bo_cso_table_148'],
 'The Martian': ['/title/tt3659388/?ref_=bo_cso_table_149'],
 'Hancock': ['/title/tt0448157/?ref_=bo_cso_table_150'],
 'Fast Five': ['/title/tt1596343/?ref_=bo_cso_table_151'],
 'Men in Black 3': ['/title/tt1409024/?ref_=bo_cso_table_152'],
 'Iron Man 2': ['/title/tt1228705/?ref_=bo_cso_table_153'],
 'Ratatouille': ['/title/tt0382932/?ref_=bo_cso_table_154'],
 'Ant-Man and the Wasp': ['/title/tt5095030/?ref_=bo_cso_table_155'],
 'How to Train Your Dragon 2': ['/title/tt1646971/?ref_=bo_cso_table_156'],
 'Logan': ['/title/tt3315342/?ref_=bo_cso_table_157'],
 'The Lost World: Jurassic Park': ['/title/tt0119567/?ref_=bo_cso_table_158'],
 'Casino Royale': ['/title/tt0381061/?ref_=bo_cso_table_159'],
 'The Passion of the Christ': ['/title/tt0335345/?ref_=bo_cso_table_160'],
 'Mamma Mia!': ['/title/tt0795421/?ref_=bo_cso_table_161'],
 'Life of Pi': ['/title/tt0454876/?ref_=bo_cso_table_162'],
 'Transformers: The Last Knight': ['/title/tt3371366/?ref_=bo_cso_table_163'],
 'Madagascar: Escape 2 Africa': ['/title/tt0479952/?ref_=bo_cso_table_164'],
 'War of the Worlds': ['/title/tt0407304/?ref_=bo_cso_table_165'],
 'Tangled': ['/title/tt0398286/?ref_=bo_cso_table_166'],
 'Quantum of Solace': ['/title/tt0830515/?ref_=bo_cso_table_167'],
 'Men in Black': ['/title/tt0119654/?ref_=bo_cso_table_168'],
 'The Croods': ['/title/tt0481499/?ref_=bo_cso_table_169'],
 'The Hangover Part II': ['/title/tt1411697/?ref_=bo_cso_table_170'],
 'Iron Man': ['/title/tt0371746/?ref_=bo_cso_table_171'],
 'I Am Legend': ['/title/tt0480249/?ref_=bo_cso_table_172'],
 'Ready Player One': ['/title/tt1677720/?ref_=bo_cso_table_173'],
 'Monsters, Inc.': ['/title/tt0198781/?ref_=bo_cso_table_174'],
 'Operation Red Sea': ['/title/tt6878882/?ref_=bo_cso_table_175'],
 'Night at the Museum': ['/title/tt0477347/?ref_=bo_cso_table_176'],
 'Fifty Shades of Grey': ['/title/tt2322441/?ref_=bo_cso_table_177'],
 'Kong: Skull Island': ['/title/tt3731562/?ref_=bo_cso_table_178'],
 'The Smurfs': ['/title/tt0472181/?ref_=bo_cso_table_179'],
 'King Kong': ['/title/tt0360717/?ref_=bo_cso_table_180'],
 'Cars 2': ['/title/tt1216475/?ref_=bo_cso_table_181'],
 'Puss in Boots': ['/title/tt0448694/?ref_=bo_cso_table_182'],
 'Mei ren yu': ['/title/tt4701660/?ref_=bo_cso_table_183'],
 'Armageddon': ['/title/tt0120591/?ref_=bo_cso_table_184'],
 'The Day After Tomorrow': ['/title/tt0319262/?ref_=bo_cso_table_185'],
 'Ted': ['/title/tt1637725/?ref_=bo_cso_table_186'],
 'American Sniper': ['/title/tt2179136/?ref_=bo_cso_table_187'],
 'Mission: Impossible II': ['/title/tt0120755/?ref_=bo_cso_table_188'],
 'Detective Chinatown 2': ['/title/tt7752454/?ref_=bo_cso_table_189'],
 'X-Men: Apocalypse': ['/title/tt3385516/?ref_=bo_cso_table_190'],
 'Sherlock Holmes: A Game of Shadows': ['/title/tt1515091/?ref_=bo_cso_table_191'],
 'Despicable Me': ['/title/tt1323594/?ref_=bo_cso_table_192'],
 'Cinderella': ['/title/tt1661199/?ref_=bo_cso_table_193'],
 'Madagascar': ['/title/tt0351283/?ref_=bo_cso_table_194'],
 'World War Z': ['/title/tt0816711/?ref_=bo_cso_table_195'],
 'Brave': ['/title/tt1217209/?ref_=bo_cso_table_196'],
 'Star Wars: Episode V - The Empire Strikes Back': ['/title/tt0080684/?ref_=bo_cso_table_197'],
 'The Simpsons Movie': ['/title/tt0462538/?ref_=bo_cso_table_198'],
 'The Revenant': ['/title/tt1663202/?ref_=bo_cso_table_199'],
 'The Meg': ['/title/tt4779682/?ref_=bo_cso_table_200']}

In [43]:
df = pd.DataFrame.from_dict(links, orient = 'index', columns = ['link'])

In [44]:
df

                                                                                   link
Avatar                                            /title/tt0499549/?ref_=bo_cso_table_1
Avengers: Endgame                                 /title/tt4154796/?ref_=bo_cso_table_2
Titanic                                           /title/tt0120338/?ref_=bo_cso_table_3
Star Wars: Episode VII - The Force Awakens        /title/tt2488496/?ref_=bo_cso_table_4
Avengers: Infinity War                            /title/tt4154756/?ref_=bo_cso_table_5
...                                                                                 ...
Brave                                           /title/tt1217209/?ref_=bo_cso_table_196
Star Wars: Episode V - The Empire Strikes Back  /title/tt0080684/?ref_=bo_cso_table_197
The Simpsons Movie                              /title/tt0462538/?ref_=bo_cso_table_198
The Revenant                                    /title/tt1663202/?ref_=bo_cso_table_199
The Meg                                         /title/tt4779682/?ref_=bo_cso_table_200

[199 rows x 1 columns]

## Getting the table

In [6]:
table = soup.find('table')

In [7]:
rows = [row for row in table.find_all('tr')]

In [8]:
rows[1]

<tr><td class="a-text-right mojo-header-column mojo-truncate mojo-field-type-rank">1</td><td class="a-text-left mojo-field-type-title"><a class="a-link-normal" href="/title/tt0499549/?ref_=bo_cso_table_1">Avatar</a></td><td class="a-text-right mojo-field-type-money">$2,847,246,203</td><td class="a-text-right mojo-field-type-money">$760,507,625</td><td class="a-text-right mojo-field-type-percent">26.7%</td><td class="a-text-right mojo-field-type-money">$2,086,738,578</td><td class="a-text-right mojo-field-type-percent">73.3%</td><td class="a-text-left mojo-field-type-year"><a class="a-link-normal" href="/year/world/2009/?ref_=bo_cso_table_1">2009</a></td></tr>

In [9]:
movies_dict = {}

for row in rows[1:]:
    items = row.find_all('td')
    link = items[1].find('a')
    title, url = link.text, link['href']
    movies_dict[title] = [url] + [i.text for i in items[1:]]
    
movies_dict

{'Avatar': ['/title/tt0499549/?ref_=bo_cso_table_1',
  'Avatar',
  '$2,847,246,203',
  '$760,507,625',
  '26.7%',
  '$2,086,738,578',
  '73.3%',
  '2009'],
 'Avengers: Endgame': ['/title/tt4154796/?ref_=bo_cso_table_2',
  'Avengers: Endgame',
  '$2,797,501,328',
  '$858,373,000',
  '30.7%',
  '$1,939,128,328',
  '69.3%',
  '2019'],
 'Titanic': ['/title/tt0120338/?ref_=bo_cso_table_3',
  'Titanic',
  '$2,201,647,264',
  '$659,363,944',
  '30%',
  '$1,542,283,320',
  '70%',
  '1997'],
 'Star Wars: Episode VII - The Force Awakens': ['/title/tt2488496/?ref_=bo_cso_table_4',
  'Star Wars: Episode VII - The Force Awakens',
  '$2,069,521,700',
  '$936,662,225',
  '45.3%',
  '$1,132,859,475',
  '54.7%',
  '2015'],
 'Avengers: Infinity War': ['/title/tt4154756/?ref_=bo_cso_table_5',
  'Avengers: Infinity War',
  '$2,048,359,754',
  '$678,815,482',
  '33.1%',
  '$1,369,544,272',
  '66.9%',
  '2018'],
 'Jurassic World': ['/title/tt0369610/?ref_=bo_cso_table_6',
  'Jurassic World',
  '$1,670,516,444',
  '$652,385,625',
  '39%',
  '$1,018,130,819',
  '61%',
  '2015'],
 'The Lion King': ['/title/tt0110357/?ref_=bo_cso_table_36',
  'The Lion King',
  '$1,063,611,805',
  '$422,783,777',
  '39.8%',
  '$640,828,028',
  '60.2%',
  '1994'],
 'The Avengers': ['/title/tt0848228/?ref_=bo_cso_table_8',
  'The Avengers',
  '$1,518,815,515',
  '$623,357,910',
  '41%',
  '$895,457,605',
  '59%',
  '2012'],
 'Furious 7': ['/title/tt2820852/?ref_=bo_cso_table_9',
  'Furious 7',
  '$1,515,341,399',
  '$353,007,020',
  '23.3%',
  '$1,162,334,379',
  '76.7%',
  '2015'],
 'Frozen II': ['/title/tt4520988/?ref_=bo_cso_table_10',
  'Frozen II',
  '$1,450,026,933',
  '$477,373,578',
  '32.9%',
  '$972,653,355',
  '67.1%',
  '2019'],
 'Avengers: Age of Ultron': ['/title/tt2395427/?ref_=bo_cso_table_11',
  'Avengers: Age of Ultron',
  '$1,402,809,540',
  '$459,005,868',
  '32.7%',
  '$943,803,672',
  '67.3%',
  '2015'],
 'Black Panther': ['/title/tt1825683/?ref_=bo_cso_table_12',
  'Black Panther',
  '$1,347,597,973',
  '$700,426,566',
  '52%',
  '$647,171,407',
  '48%',
  '2018'],
 'Harry Potter and the Deathly Hallows: Part 2': ['/title/tt1201607/?ref_=bo_cso_table_13',
  'Harry Potter and the Deathly Hallows: Part 2',
  '$1,342,321,665',
  '$381,409,310',
  '28.4%',
  '$960,912,355',
  '71.6%',
  '2011'],
 'Star Wars: Episode VIII - The Last Jedi': ['/title/tt2527336/?ref_=bo_cso_table_14',
  'Star Wars: Episode VIII - The Last Jedi',
  '$1,332,698,830',
  '$620,181,382',
  '46.5%',
  '$712,517,448',
  '53.5%',
  '2017'],
 'Jurassic World: Fallen Kingdom': ['/title/tt4881806/?ref_=bo_cso_table_15',
  'Jurassic World: Fallen Kingdom',
  '$1,310,466,296',
  '$417,719,760',
  '31.9%',
  '$892,746,536',
  '68.1%',
  '2018'],
 'Frozen': ['/title/tt2294629/?ref_=bo_cso_table_16',
  'Frozen',
  '$1,281,508,100',
  '$400,953,009',
  '31.3%',
  '$880,555,091',
  '68.7%',
  '2013'],
 'Beauty and the Beast': ['/title/tt2771200/?ref_=bo_cso_table_17',
  'Beauty and the Beast',
  '$1,264,434,525',
  '$504,481,165',
  '39.9%',
  '$759,953,360',
  '60.1%',
  '2017'],
 'Incredibles 2': ['/title/tt3606756/?ref_=bo_cso_table_18',
  'Incredibles 2',
  '$1,244,639,527',
  '$608,581,744',
  '48.9%',
  '$636,057,783',
  '51.1%',
  '2018'],
 'The Fate of the Furious': ['/title/tt4630562/?ref_=bo_cso_table_19',
  'The Fate of the Furious',
  '$1,236,005,118',
  '$226,008,385',
  '18.3%',
  '$1,009,996,733',
  '81.7%',
  '2017'],
 'Iron Man 3': ['/title/tt1300854/?ref_=bo_cso_table_20',
  'Iron Man 3',
  '$1,214,811,252',
  '$409,013,994',
  '33.7%',
  '$805,797,258',
  '66.3%',
  '2013'],
 'Minions': ['/title/tt2293640/?ref_=bo_cso_table_21',
  'Minions',
  '$1,159,444,662',
  '$336,045,770',
  '29%',
  '$823,398,892',
  '71%',
  '2015'],
 'Captain America: Civil War': ['/title/tt3498820/?ref_=bo_cso_table_22',
  'Captain America: Civil War',
  '$1,153,337,496',
  '$408,084,349',
  '35.4%',
  '$745,253,147',
  '64.6%',
  '2016'],
 'Aquaman': ['/title/tt1477834/?ref_=bo_cso_table_23',
  'Aquaman',
  '$1,148,485,886',
  '$335,061,807',
  '29.2%',
  '$813,424,079',
  '70.8%',
  '2018'],
 'The Lord of the Rings: The Return of the King': ['/title/tt0167260/?ref_=bo_cso_table_24',
  'The Lord of the Rings: The Return of the King',
  '$1,146,030,912',
  '$377,845,905',
  '33%',
  '$768,185,007',
  '67%',
  '2003'],
 'Spider-Man: Far from Home': ['/title/tt6320628/?ref_=bo_cso_table_25',
  'Spider-Man: Far from Home',
  '$1,131,927,996',
  '$390,532,085',
  '34.5%',
  '$741,395,911',
  '65.5%',
  '2019'],
 'Captain Marvel': ['/title/tt4154664/?ref_=bo_cso_table_26',
  'Captain Marvel',
  '$1,128,462,972',
  '$426,829,839',
  '37.8%',
  '$701,633,133',
  '62.2%',
  '2019'],
 'Transformers: Dark of the Moon': ['/title/tt1399103/?ref_=bo_cso_table_27',
  'Transformers: Dark of the Moon',
  '$1,123,794,079',
  '$352,390,543',
  '31.4%',
  '$771,403,536',
  '68.6%',
  '2011'],
 'Skyfall': ['/title/tt1074638/?ref_=bo_cso_table_28',
  'Skyfall',
  '$1,108,569,499',
  '$304,360,277',
  '27.5%',
  '$804,209,222',
  '72.5%',
  '2012'],
 'Transformers: Age of Extinction': ['/title/tt2109248/?ref_=bo_cso_table_29',
  'Transformers: Age of Extinction',
  '$1,104,054,072',
  '$245,439,076',
  '22.2%',
  '$858,614,996',
  '77.8%',
  '2014'],
 'The Dark Knight Rises': ['/title/tt1345836/?ref_=bo_cso_table_30',
  'The Dark Knight Rises',
  '$1,081,142,612',
  '$448,139,099',
  '41.4%',
  '$633,003,513',
  '58.6%',
  '2012'],
 'Star Wars: Episode IX - The Rise of Skywalker': ['/title/tt2527338/?ref_=bo_cso_table_31',
  'Star Wars: Episode IX - The Rise of Skywalker',
  '$1,078,232,589',
  '$515,202,542',
  '47.8%',
  '$563,030,047',
  '52.2%',
  '2019'],
 'Joker': ['/title/tt7286456/?ref_=bo_cso_table_32',
  'Joker',
  '$1,074,419,384',
  '$335,451,311',
  '31.2%',
  '$738,968,073',
  '68.8%',
  '2019'],
 'Toy Story 4': ['/title/tt1979376/?ref_=bo_cso_table_33',
  'Toy Story 4',
  '$1,073,394,593',
  '$434,038,008',
  '40.4%',
  '$639,356,585',
  '59.6%',
  '2019'],
 'Toy Story 3': ['/title/tt0435761/?ref_=bo_cso_table_34',
  'Toy Story 3',
  '$1,066,970,811',
  '$415,004,880',
  '38.9%',
  '$651,965,931',
  '61.1%',
  '2010'],
 "Pirates of the Caribbean: Dead Man's Chest": ['/title/tt0383574/?ref_=bo_cso_table_35',
  "Pirates of the Caribbean: Dead Man's Chest",
  '$1,066,179,747',
  '$423,315,812',
  '39.7%',
  '$642,863,935',
  '60.3%',
  '2006'],
 'Rogue One: A Star Wars Story': ['/title/tt3748528/?ref_=bo_cso_table_37',
  'Rogue One: A Star Wars Story',
  '$1,056,057,720',
  '$532,177,324',
  '50.4%',
  '$523,880,396',
  '49.6%',
  '2016'],
 'Aladdin': ['/title/tt6139732/?ref_=bo_cso_table_38',
  'Aladdin',
  '$1,050,693,953',
  '$355,559,216',
  '33.8%',
  '$695,134,737',
  '66.2%',
  '2019'],
 'Pirates of the Caribbean: On Stranger Tides': ['/title/tt1298650/?ref_=bo_cso_table_39',
  'Pirates of the Caribbean: On Stranger Tides',
  '$1,045,713,802',
  '$241,071,802',
  '23%',
  '$804,642,000',
  '77%',
  '2011'],
 'Despicable Me 3': ['/title/tt3469046/?ref_=bo_cso_table_40',
  'Despicable Me 3',
  '$1,034,800,131',
  '$264,624,300',
  '25.6%',
  '$770,175,831',
  '74.4%',
  '2017'],
 'Jurassic Park': ['/title/tt0107290/?ref_=bo_cso_table_41',
  'Jurassic Park',
  '$1,033,928,303',
  '$404,214,720',
  '39.1%',
  '$629,713,583',
  '60.9%',
  '1993'],
 'Finding Dory': ['/title/tt2277860/?ref_=bo_cso_table_42',
  'Finding Dory',
  '$1,028,570,942',
  '$486,295,561',
  '47.3%',
  '$542,275,381',
  '52.7%',
  '2016'],
 'Star Wars: Episode I - The Phantom Menace': ['/title/tt0120915/?ref_=bo_cso_table_43',
  'Star Wars: Episode I - The Phantom Menace',
  '$1,027,082,707',
  '$474,544,677',
  '46.2%',
  '$552,538,030',
  '53.8%',
  '1999'],
 'Alice in Wonderland': ['/title/tt1014759/?ref_=bo_cso_table_44',
  'Alice in Wonderland',
  '$1,025,468,216',
  '$334,191,110',
  '32.6%',
  '$691,277,106',
  '67.4%',
  '2010'],
 'Zootopia': ['/title/tt2948356/?ref_=bo_cso_table_45',
  'Zootopia',
  '$1,024,121,104',
  '$341,268,248',
  '33.3%',
  '$682,852,856',
  '66.7%',
  '2016'],
 'The Hobbit: An Unexpected Journey': ['/title/tt0903624/?ref_=bo_cso_table_46',
  'The Hobbit: An Unexpected Journey',
  '$1,017,003,568',
  '$303,003,568',
  '29.8%',
  '$714,000,000',
  '70.2%',
  '2012'],
 "Harry Potter and the Sorcerer's Stone": ['/title/tt0241527/?ref_=bo_cso_table_47',
  "Harry Potter and the Sorcerer's Stone",
  '$1,009,281,898',
  '$318,087,620',
  '31.5%',
  '$691,194,278',
  '68.5%',
  '2001'],
 'The Dark Knight': ['/title/tt0468569/?ref_=bo_cso_table_48',
  'The Dark Knight',
  '$1,005,973,645',
  '$534,858,444',
  '53.2%',
  '$471,115,201',
  '46.8%',
  '2008'],
 'Harry Potter and the Deathly Hallows: Part 1': ['/title/tt0926084/?ref_=bo_cso_table_49',
  'Harry Potter and the Deathly Hallows: Part 1',
  '$977,043,483',
  '$296,347,721',
  '30.3%',
  '$680,695,762',
  '69.7%',
  '2010'],
 'Despicable Me 2': ['/title/tt1690953/?ref_=bo_cso_table_50',
  'Despicable Me 2',
  '$970,766,005',
  '$368,065,385',
  '37.9%',
  '$602,700,620',
  '62.1%',
  '2013'],
 'The Jungle Book': ['/title/tt3040964/?ref_=bo_cso_table_51',
  'The Jungle Book',
  '$966,554,929',
  '$364,001,123',
  '37.7%',
  '$602,553,806',
  '62.3%',
  '2016'],
 'Jumanji: Welcome to the Jungle': ['/title/tt2283362/?ref_=bo_cso_table_52',
  'Jumanji: Welcome to the Jungle',
  '$962,542,945',
  '$404,540,171',
  '42%',
  '$558,002,774',
  '58%',
  '2017'],
 'The Hobbit: The Battle of the Five Armies': ['/title/tt2310332/?ref_=bo_cso_table_53',
  'The Hobbit: The Battle of the Five Armies',
  '$962,182,865',
  '$255,119,788',
  '26.5%',
  '$707,063,077',
  '73.5%',
  '2014'],
 "Pirates of the Caribbean: At World's End": ['/title/tt0449088/?ref_=bo_cso_table_54',
  "Pirates of the Caribbean: At World's End",
  '$960,996,492',
  '$309,420,425',
  '32.2%',
  '$651,576,067',
  '67.8%',
  '2007'],
 'The Hobbit: The Desolation of Smaug': ['/title/tt1170358/?ref_=bo_cso_table_55',
  'The Hobbit: The Desolation of Smaug',
  '$959,007,513',
  '$258,366,855',
  '26.9%',
  '$700,640,658',
  '73.1%',
  '2013'],
 'The Lord of the Rings: The Two Towers': ['/title/tt0167261/?ref_=bo_cso_table_56',
  'The Lord of the Rings: The Two Towers',
  '$947,495,095',
  '$342,551,365',
  '36.2%',
  '$604,943,730',
  '63.8%',
  '2002'],
 'Harry Potter and the Order of the Phoenix': ['/title/tt0373889/?ref_=bo_cso_table_57',
  'Harry Potter and the Order of the Phoenix',
  '$942,172,396',
  '$292,353,413',
  '31%',
  '$649,818,983',
  '69%',
  '2007'],
 'Finding Nemo': ['/title/tt0266543/?ref_=bo_cso_table_58',
  'Finding Nemo',
  '$940,352,645',
  '$380,843,261',
  '40.5%',
  '$559,509,384',
  '59.5%',
  '2003'],
 'Harry Potter and the Half-Blood Prince': ['/title/tt0417741/?ref_=bo_cso_table_59',
  'Harry Potter and the Half-Blood Prince',
  '$934,454,096',
  '$302,305,431',
  '32.4%',
  '$632,148,665',
  '67.6%',
  '2009'],
 'Shrek 2': ['/title/tt0298148/?ref_=bo_cso_table_60',
  'Shrek 2',
  '$928,760,770',
  '$441,226,247',
  '47.5%',
  '$487,534,523',
  '52.5%',
  '2004'],
 'Bohemian Rhapsody': ['/title/tt1727824/?ref_=bo_cso_table_61',
  'Bohemian Rhapsody',
  '$911,100,727',
  '$216,668,042',
  '23.8%',
  '$694,432,685',
  '76.2%',
  '2018'],
 'The Lord of the Rings: The Fellowship of the Ring': ['/title/tt0120737/?ref_=bo_cso_table_62',
  'The Lord of the Rings: The Fellowship of the Ring',
  '$897,690,072',
  '$315,710,750',
  '35.2%',
  '$581,979,322',
  '64.8%',
  '2001'],
 'Harry Potter and the Goblet of Fire': ['/title/tt0330373/?ref_=bo_cso_table_63',
  'Harry Potter and the Goblet of Fire',
  '$896,678,241',
  '$290,417,905',
  '32.4%',
  '$606,260,336',
  '67.6%',
  '2005'],
 'Spider-Man 3': ['/title/tt0413300/?ref_=bo_cso_table_64',
  'Spider-Man 3',
  '$894,983,373',
  '$336,530,303',
  '37.6%',
  '$558,453,070',
  '62.4%',
  '2007'],
 'Ice Age: Dawn of the Dinosaurs': ['/title/tt1080016/?ref_=bo_cso_table_65',
  'Ice Age: Dawn of the Dinosaurs',
  '$886,686,817',
  '$196,573,705',
  '22.2%',
  '$690,113,112',
  '77.8%',
  '2009'],
 'Spectre': ['/title/tt2379713/?ref_=bo_cso_table_66',
  'Spectre',
  '$880,681,519',
  '$200,074,609',
  '22.7%',
  '$680,606,910',
  '77.3%',
  '2015'],
 'Spider-Man: Homecoming': ['/title/tt2250912/?ref_=bo_cso_table_67',
  'Spider-Man: Homecoming',
  '$880,166,924',
  '$334,201,140',
  '38%',
  '$545,965,784',
  '62%',
  '2017'],
 'Harry Potter and the Chamber of Secrets': ['/title/tt0295297/?ref_=bo_cso_table_68',
  'Harry Potter and the Chamber of Secrets',
  '$879,602,366',
  '$262,450,136',
  '29.8%',
  '$617,152,230',
  '70.2%',
  '2002'],
 'Ice Age: Continental Drift': ['/title/tt1667889/?ref_=bo_cso_table_69',
  'Ice Age: Continental Drift',
  '$877,244,782',
  '$161,321,843',
  '18.4%',
  '$715,922,939',
  '81.6%',
  '2012'],
 'The Secret Life of Pets': ['/title/tt2709768/?ref_=bo_cso_table_70',
  'The Secret Life of Pets',
  '$875,458,631',
  '$368,384,330',
  '42.1%',
  '$507,074,301',
  '57.9%',
  '2016'],
 'Batman v Superman: Dawn of Justice': ['/title/tt2975590/?ref_=bo_cso_table_71',
  'Batman v Superman: Dawn of Justice',
  '$873,637,528',
  '$330,360,194',
  '37.8%',
  '$543,277,334',
  '62.2%',
  '2016'],
 'Wolf Warrior 2': ['/title/tt7131870/?ref_=bo_cso_table_72',
  'Wolf Warrior 2',
  '$870,325,439',
  '$2,721,100',
  '0.3%',
  '$867,604,339',
  '99.7%',
  '2017'],
 'Star Wars: Episode III - Revenge of the Sith': ['/title/tt0121766/?ref_=bo_cso_table_73',
  'Star Wars: Episode III - Revenge of the Sith',
  '$868,390,560',
  '$380,270,577',
  '43.8%',
  '$488,119,983',
  '56.2%',
  '2005'],
 'The Hunger Games: Catching Fire': ['/title/tt1951264/?ref_=bo_cso_table_74',
  'The Hunger Games: Catching Fire',
  '$865,011,746',
  '$424,668,047',
  '49.1%',
  '$440,343,699',
  '50.9%',
  '2013'],
 'Guardians of the Galaxy Vol. 2': ['/title/tt3896198/?ref_=bo_cso_table_75',
  'Guardians of the Galaxy Vol. 2',
  '$863,756,051',
  '$389,813,101',
  '45.1%',
  '$473,942,950',
  '54.9%',
  '2017'],
 'Inside Out': ['/title/tt2096673/?ref_=bo_cso_table_76',
  'Inside Out',
  '$858,848,019',
  '$356,921,711',
  '41.6%',
  '$501,926,308',
  '58.4%',
  '2015'],
 'Venom': ['/title/tt1270797/?ref_=bo_cso_table_77',
  'Venom',
  '$856,085,151',
  '$213,515,506',
  '24.9%',
  '$642,569,645',
  '75.1%',
  '2018'],
 'Thor: Ragnarok': ['/title/tt3501632/?ref_=bo_cso_table_78',
  'Thor: Ragnarok',
  '$853,983,911',
  '$315,058,289',
  '36.9%',
  '$538,925,622',
  '63.1%',
  '2017'],
 'Inception': ['/title/tt1375666/?ref_=bo_cso_table_79',
  'Inception',
  '$836,836,967',
  '$292,576,195',
  '35%',
  '$544,260,772',
  '65%',
  '2010'],
 'Transformers: Revenge of the Fallen': ['/title/tt1055369/?ref_=bo_cso_table_80',
  'Transformers: Revenge of the Fallen',
  '$836,303,693',
  '$402,111,870',
  '48.1%',
  '$434,191,823',
  '51.9%',
  '2009'],
 'The Twilight Saga: Breaking Dawn - Part 2': ['/title/tt1673434/?ref_=bo_cso_table_81',
  'The Twilight Saga: Breaking Dawn - Part 2',
  '$829,747,654',
  '$292,324,737',
  '35.2%',
  '$537,422,917',
  '64.8%',
  '2012'],
 'Spider-Man': ['/title/tt0145487/?ref_=bo_cso_table_82',
  'Spider-Man',
  '$825,025,036',
  '$407,022,860',
  '49.3%',
  '$418,002,176',
  '50.7%',
  '2002'],
 'Wonder Woman': ['/title/tt0451279/?ref_=bo_cso_table_83',
  'Wonder Woman',
  '$822,824,522',
  '$412,815,408',
  '50.2%',
  '$410,009,114',
  '49.8%',
  '2017'],
 'Hi, Mom': ['/title/tt13364790/?ref_=bo_cso_table_84',
  'Hi, Mom',
  '$822,009,764',
  '-',
  '-',
  '$822,009,764',
  '100%',
  '2021'],
 'Independence Day': ['/title/tt0116629/?ref_=bo_cso_table_85',
  'Independence Day',
  '$817,400,891',
  '$306,169,268',
  '37.5%',
  '$511,231,623',
  '62.5%',
  '1996'],
 'Fantastic Beasts and Where to Find Them': ['/title/tt3183660/?ref_=bo_cso_table_86',
  'Fantastic Beasts and Where to Find Them',
  '$814,044,001',
  '$234,037,575',
  '28.8%',
  '$580,006,426',
  '71.2%',
  '2016'],
 'Shrek the Third': ['/title/tt0413267/?ref_=bo_cso_table_87',
  'Shrek the Third',
  '$813,367,380',
  '$322,719,944',
  '39.7%',
  '$490,647,436',
  '60.3%',
  '2007'],
 'Coco': ['/title/tt2380307/?ref_=bo_cso_table_88',
  'Coco',
  '$807,817,888',
  '$210,460,015',
  '26%',
  '$597,357,873',
  '74%',
  '2017'],
 'Jumanji: The Next Level': ['/title/tt7975244/?ref_=bo_cso_table_89',
  'Jumanji: The Next Level',
  '$800,059,707',
  '$320,314,960',
  '40%',
  '$479,744,747',
  '60%',
  '2019'],
 'Harry Potter and the Prisoner of Azkaban': ['/title/tt0304141/?ref_=bo_cso_table_90',
  'Harry Potter and the Prisoner of Azkaban',
  '$797,361,618',
  '$249,975,996',
  '31.4%',
  '$547,385,622',
  '68.6%',
  '2004'],
 'Pirates of the Caribbean: Dead Men Tell No Tales': ['/title/tt1790809/?ref_=bo_cso_table_91',
  'Pirates of the Caribbean: Dead Men Tell No Tales',
  '$794,881,442',
  '$172,558,876',
  '21.7%',
  '$622,322,566',
  '78.3%',
  '2017'],
 'E.T. the Extra-Terrestrial': ['/title/tt0083866/?ref_=bo_cso_table_92',
  'E.T. the Extra-Terrestrial',
  '$792,910,554',
  '$435,110,554',
  '54.9%',
  '$357,800,000',
  '45.1%',
  '1982'],
 'Mission: Impossible - Fallout': ['/title/tt4912910/?ref_=bo_cso_table_93',
  'Mission: Impossible - Fallout',
  '$791,657,398',
  '$220,159,104',
  '27.8%',
  '$571,498,294',
  '72.2%',
  '2018'],
 '2012': ['/title/tt1190080/?ref_=bo_cso_table_94',
  '2012',
  '$791,217,826',
  '$166,112,167',
  '21%',
  '$625,105,659',
  '79%',
  '2009'],
 'Indiana Jones and the Kingdom of the Crystal Skull': ['/title/tt0367882/?ref_=bo_cso_table_95',
  'Indiana Jones and the Kingdom of the Crystal Skull',
  '$790,653,942',
  '$317,101,119',
  '40.1%',
  '$473,552,823',
  '59.9%',
  '2008'],
 'Spider-Man 2': ['/title/tt0316654/?ref_=bo_cso_table_96',
  'Spider-Man 2',
  '$788,976,453',
  '$373,585,825',
  '47.4%',
  '$415,390,628',
  '52.6%',
  '2004'],
 'Fast & Furious 6': ['/title/tt1905041/?ref_=bo_cso_table_97',
  'Fast & Furious 6',
  '$788,680,968',
  '$238,679,850',
  '30.3%',
  '$550,001,118',
  '69.7%',
  '2013'],
 'Deadpool 2': ['/title/tt5463162/?ref_=bo_cso_table_98',
  'Deadpool 2',
  '$786,470,484',
  '$324,591,735',
  '41.3%',
  '$461,878,749',
  '58.7%',
  '2018'],
 'Deadpool': ['/title/tt1431045/?ref_=bo_cso_table_99',
  'Deadpool',
  '$782,836,791',
  '$363,070,709',
  '46.4%',
  '$419,766,082',
  '53.6%',
  '2016'],
 'Star Wars: Episode IV - A New Hope': ['/title/tt0076759/?ref_=bo_cso_table_100',
  'Star Wars: Episode IV - A New Hope',
  '$775,398,007',
  '$460,998,507',
  '59.4%',
  '$314,399,500',
  '40.6%',
  '1977'],
 'Guardians of the Galaxy': ['/title/tt2015381/?ref_=bo_cso_table_101',
  'Guardians of the Galaxy',
  '$773,350,147',
  '$333,718,600',
  '43.2%',
  '$439,631,547',
  '56.8%',
  '2014'],
 'The Da Vinci Code': ['/title/tt0382625/?ref_=bo_cso_table_102',
  'The Da Vinci Code',
  '$760,006,945',
  '$217,536,138',
  '28.6%',
  '$542,470,807',
  '71.4%',
  '2006'],
 'Fast & Furious Presents: Hobbs & Shaw': ['/title/tt6806448/?ref_=bo_cso_table_103',
  'Fast & Furious Presents: Hobbs & Shaw',
  '$759,056,935',
  '$173,956,935',
  '22.9%',
  '$585,100,000',
  '77.1%',
  '2019'],
 'Maleficent': ['/title/tt1587310/?ref_=bo_cso_table_104',
  'Maleficent',
  '$758,411,779',
  '$241,410,378',
  '31.8%',
  '$517,001,401',
  '68.2%',
  '2014'],
 'The Amazing Spider-Man': ['/title/tt0948470/?ref_=bo_cso_table_105',
  'The Amazing Spider-Man',
  '$757,930,663',
  '$262,030,663',
  '34.6%',
  '$495,900,000',
  '65.4%',
  '2012'],
 'The Hunger Games: Mockingjay - Part 1': ['/title/tt1951265/?ref_=bo_cso_table_106',
  'The Hunger Games: Mockingjay - Part 1',
  '$755,356,711',
  '$337,135,885',
  '44.6%',
  '$418,220,826',
  '55.4%',
  '2014'],
 'Shrek Forever After': ['/title/tt0892791/?ref_=bo_cso_table_107',
  'Shrek Forever After',
  '$752,600,867',
  '$238,736,787',
  '31.7%',
  '$513,864,080',
  '68.3%',
  '2010'],
 "Madagascar 3: Europe's Most Wanted": ['/title/tt1277953/?ref_=bo_cso_table_108',
  "Madagascar 3: Europe's Most Wanted",
  '$746,921,274',
  '$216,391,482',
  '29%',

In [28]:
movies_df = pd.DataFrame(movies_dict).T  #transpose
movies_df.columns = ['link_stub', 'title', 'World Lifetime Gross', 
                    'Domestic Lifetime Gross', 'Domestic %', 
                    'Foreign Lifetime Gross', 'Foreign %', 'year']

movies_df

,link_stub,title,World Lifetime Gross,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,year
Avatar,/title/tt0499549/?ref_=bo_cso_table_1,Avatar,"$2,847,246,203","$760,507,625",26.7%,"$2,086,738,578",73.3%,2009
Avengers: Endgame,/title/tt4154796/?ref_=bo_cso_table_2,Avengers: Endgame,"$2,797,501,328","$858,373,000",30.7%,"$1,939,128,328",69.3%,2019
Titanic,/title/tt0120338/?ref_=bo_cso_table_3,Titanic,"$2,201,647,264","$659,363,944",30%,"$1,542,283,320",70%,1997
Star Wars: Episode VII - The Force Awakens,/title/tt2488496/?ref_=bo_cso_table_4,Star Wars: Episode VII - The Force Awakens,"$2,069,521,700","$936,662,225",45.3%,"$1,132,859,475",54.7%,2015
Avengers: Infinity War,/title/tt4154756/?ref_=bo_cso_table_5,Avengers: Infinity War,"$2,048,359,754","$678,815,482",33.1%,"$1,369,544,272",66.9%,2018
...,...,...,...,...,...,...,...,...
Brave,/title/tt1217209/?ref_=bo_cso_table_196,Brave,"$538,983,207","$237,283,207",44%,"$301,700,000",56%,2012
Star Wars: Episode V - The Empire Strikes Back,/title/tt0080684/?ref_=bo_cso_table_197,Star Wars: Episode V - The Empire Strikes Back,"$538,375,067","$292,753,960",54.4%,"$245,621,107",45.6%,1980
The Simpsons Movie,/title/tt0462538/?ref_=bo_cso_table_198,The Simpsons Movie,"$536,414,293","$183,135,014",34.1%,"$353,279,279",65.9%,2007
The Revenant,/title/tt1663202/?ref_=bo_cso_table_199,The Revenant,"$532,950,503","$183,637,894",34.5%,"$349,312,609",65.5%,2015
The Meg,/title/tt4779682/?ref_=bo_cso_table_200,The Meg,"$530,259,473","$145,443,742",27.4%,"$384,815,731",72.6%,2018

### Function getting movie values

In [39]:
def get_movie_value(soup, field_name):
    
    '''Grab a value from Box Office Mojo HTML
    
    Takes a string attribute of a movie on the page and returns the string in
    the next sibling object (the value for that attribute) or None if nothing is found.
    '''
    
    obj = soup.find(text=re.compile(field_name))
    
    if not obj: 
        return None
    
    # this works for most of the values
    next_element = obj.findNext()
    
    if next_element:
        return next_element.text 
    else:
        return None

### All useful functions to clean data

In [40]:
import dateutil.parser

def money_to_int(moneystring):
    moneystring = moneystring.replace('$', '').replace(',', '').replace('-','')
    try:
        return int(moneystring)
    except ValueError:
        return 0

def runtime_to_minutes(runtimestring):
    runtime = runtimestring.split()
    try:
        minutes = int(runtime[0])*60 + int(runtime[2])
        return minutes
    except:
        return 0

def to_date(datestring):
    date = dateutil.parser.parse(datestring)
    return date

### Getting all movie items into dataframe

In [41]:
def get_movie_items(row):
    base_url = 'https://www.boxofficemojo.com'
    
    #Create full url to scrape
    url = base_url + row['link_stub']
    
    #Request HTML and parse
    response = requests.get(url)
    page = response.text
    soup = BeautifulSoup(page,"lxml")
    
    #Getting domestic distributor
    try:
        row['Domestic Distributor'] = (get_movie_value(soup,'Domestic Distributor')
                                       .replace('See full company information',''))
    except AttributeError:
        row['Domestic Distributor'] = ''
        
    
    #Getting domestic opening
    try:
        row['Domestic Opening'] = money_to_int(get_movie_value(soup,'Domestic Opening'))
    except AttributeError:
        row['Domestic Opening'] = 0
    
    #Getting budget
    try:
        budget = get_movie_value(soup,'Budget')
        row['budget'] = money_to_int(budget)
    except AttributeError:
        row['budget'] = 0
    
    #Getting MPAA rating
    try:
        row['MPAA'] = get_movie_value(soup,'MPAA')
    except AttributeError:
        row['MPAA'] = ''
        
    #Getting running time
    try:
        row['Running Time'] = runtime_to_minutes(get_movie_value(soup,'Run'))
    except AttributeError:
        row['Running Time'] = 0
    
    #Getting genres
    try:
        genres = (get_movie_value(soup,'Genres').replace(' ','')
                  .replace('\n','').replace('Sci-Fi','Science fiction'))
        row['genres'] = re.findall('[A-Z][^A-Z]*', genres)
    except AttributeError:
        row['genres'] = ''
    
    ##Getting Original Release values
    if (soup.find_all('h3')[0].text == 'By Release'):
        original_release_domestic = soup.find('table').find_all('td')[3].text
        row['Original Release Domestic'] = money_to_int(original_release_domestic)
        original_release_international = soup.find('table').find_all('td')[4].text
        row['Original Release International'] = money_to_int(original_release_international)
        original_release_worldwide = soup.find('table').find_all('td')[5].text
        row['Original Release Worldwide'] = money_to_int(original_release_worldwide)
    else:
        row['Original Release Domestic'] = money_to_int(row['Domestic Lifetime Gross'])
        row['Original Release International'] = money_to_int(row['Foreign Lifetime Gross'])
        row['Original Release Worldwide'] = money_to_int(row['World Lifetime Gross'])
        
    return row

In [42]:
movies_df = movies_df.apply(get_movie_items, axis = 1)

In [44]:
movies_df

,link_stub,title,World Lifetime Gross,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,year,Domestic Distributor,Domestic Opening,budget,MPAA,Running Time,genres,Original Release Domestic,Original Release International,Original Release Worldwide
Avatar,/title/tt0499549/?ref_=bo_cso_table_1,Avatar,"$2,847,246,203","$760,507,625",26.7%,"$2,086,738,578",73.3%,2009,Twentieth Century Fox\n\n,77025481,237000000,PG-13,162,"[Action, Adventure, Fantasy, Science fiction]",749766139,1993811448,2743577587
Avengers: Endgame,/title/tt4154796/?ref_=bo_cso_table_2,Avengers: Endgame,"$2,797,501,328","$858,373,000",30.7%,"$1,939,128,328",69.3%,2019,Walt Disney Studios Motion Pictures\n\n,357115007,356000000,PG-13,181,"[Action, Adventure, Drama, Science fiction]",858373000,1939128328,2797501328
Titanic,/title/tt0120338/?ref_=bo_cso_table_3,Titanic,"$2,201,647,264","$659,363,944",30%,"$1,542,283,320",70%,1997,Paramount Pictures\n\n,28638131,200000000,PG-13,194,"[Drama, Romance]",600788188,1242690261,1843478449
Star Wars: Episode VII - The Force Awakens,/title/tt2488496/?ref_=bo_cso_table_4,Star Wars: Episode VII - The Force Awakens,"$2,069,521,700","$936,662,225",45.3%,"$1,132,859,475",54.7%,2015,Walt Disney Studios Motion Pictures\n\n,247966675,245000000,PG-13,138,"[Action, Adventure, Science fiction]",936662225,1131561399,2068223624
Avengers: Infinity War,/title/tt4154756/?ref_=bo_cso_table_5,Avengers: Infinity War,"$2,048,359,754","$678,815,482",33.1%,"$1,369,544,272",66.9%,2018,Walt Disney Studios Motion Pictures\n\n,257698183,0,PG-13,149,"[Action, Adventure, Science fiction]",678815482,1369544272,2048359754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Brave,/title/tt1217209/?ref_=bo_cso_table_196,Brave,"$538,983,207","$237,283,207",44%,"$301,700,000",56%,2012,Walt Disney Studios Motion Pictures\n\n,66323594,185000000,PG,93,"[Adventure, Animation, Comedy, Family, Fantasy]",237283207,301700000,538983207
Star Wars: Episode V - The Empire Strikes Back,/title/tt0080684/?ref_=bo_cso_table_197,Star Wars: Episode V - The Empire Strikes Back,"$538,375,067","$292,753,960",54.4%,"$245,621,107",45.6%,1980,Twentieth Century Fox\n\n,4910483,18000000,PG,124,"[Action, Adventure, Fantasy, Science fiction]",209398025,0,209398025
The Simpsons Movie,/title/tt0462538/?ref_=bo_cso_table_198,The Simpsons Movie,"$536,414,293","$183,135,014",34.1%,"$353,279,279",65.9%,2007,Twentieth Century Fox\n\n,74036787,75000000,PG-13,87,"[Adventure, Animation, Comedy]",183135014,353279256,536414270
The Revenant,/title/tt1663202/?ref_=bo_cso_table_199,The Revenant,"$532,950,503","$183,637,894",34.5%,"$349,312,609",65.5%,2015,Twentieth Century Fox\n\n,474560,135000000,R,156,"[Action, Adventure, Drama, History, Western]",183637894,349312609,532950503
The Meg,/title/tt4779682/?ref_=bo_cso_table_200,The Meg,"$530,259,473","$145,443,742",27.4%,"$384,815,731",72.6%,2018,Warner Bros.\n\n,45402195,130000000,PG-13,113,"[Action, Horror, Science fiction, Thriller]",145443742,384800000,530243742